# Generated by Django 5.2.7 on 2025-10-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
